### ISSUE TITLE
Image crop for candidate card with multiple candidacies

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/design-system#10]
### Issue and Steps to Reproduce

While working on the [new Person Page](https://github.com/DemocracyClub/WhoCanIVoteFor/pull/660), I noticed the candidate images are awkwardly cropped in some cases.

One candidacy: http://localhost:8000/person/7842/tony-devenish
Many candidacies: http://localhost:8000/person/1478/shaun-bailey

### Screenshots
While the image for a candidate with one candidacy looks great:
<img width="982" alt="Screen Shot 2021-02-24 at 10 19 44 AM" src="https://user-images.githubusercontent.com/7017118/109024715-0b2e1300-768c-11eb-8174-285dd736f951.png">
The image for a candidate with more than one candidacy is less so: 
<img width="983" alt="Screen Shot 2021-02-24 at 10 19 25 AM" src="https://user-images.githubusercontent.com/7017118/109024738-0ec19a00-768c-11eb-9ac6-bf98b8b4af9f.png">

**Comment by Heydon** [comment]
@VirginiaDooley Okay, I've adjusted this here: https://github.com/DemocracyClub/design-system/commit/cb49071ee3b1f940b5956d3e34c04aa48e1801b6

Bear in mind it’s always going to be an imperfect algorithm to get the card image effect across all viewport dimensions without loads of redundant white-space or stretching the image.

<img width="825" alt="example of the adjusted layout" src="https://user-images.githubusercontent.com/683558/109820768-36d17000-7c2d-11eb-966a-0548e53fa935.png">
