### ISSUE TITLE
Breadcrumbs break card layouts

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/design-system#12]
### Issue and Steps to Reproduce
On https://whocanivotefor.co.uk/person/73214/david-fraser with on a narrow window / device the cards and breadcrumbs interact in not ideal ways

### Screenshots
![Screenshot from 2021-03-09 11-56-24](https://user-images.githubusercontent.com/242329/110467347-d16afc80-80ce-11eb-9661-179c96d3441d.png)

#### Expected
Adding `overflow: auto` to `.breadcrumbs` deals with this, but that might not be the best solution:

![Screenshot from 2021-03-09 11-59-03](https://user-images.githubusercontent.com/242329/110467447-efd0f800-80ce-11eb-9cad-86bb89a97d65.png)

### Additional Details
* Browser and version
Firefox, Ubuntu

**Comment by pmk01** [comment]
Here's how it looks on my mobile. The table of previous elections also doesn't collapse down, meaning I need to scroll left-right on it.


![Screenshot_20210309-154506](https://user-images.githubusercontent.com/61510609/110498637-6b42a180-80ef-11eb-9797-eb84a88589c1.png)

**Comment by symroe** [comment]
FYI the table not collapsing is by design. See "Responsiveness" on https://democracyclub.github.io/design-system/components/table/

**Comment by pmk01** [comment]
OK! I did wonder. Tables are a tricky business, I guess.

**Comment by pmk01** [comment]
Mine is improved, but still awkward. When I try landscape view the photo becomes _enormous_.

![Screenshot_20210311-230502](https://user-images.githubusercontent.com/61510609/110924801-6281e380-831a-11eb-80f3-71c7ef9f6e35.png)
![Screenshot_20210311-230428](https://user-images.githubusercontent.com/61510609/110924809-63b31080-831a-11eb-9b15-ab656e08aff2.png)
