### ISSUE TITLE
More cards per page on mobile view

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/design-system#18]
Originally raised in https://github.com/DemocracyClub/WhoCanIVoteFor/issues/585

After implementing the design system for `people-lists`, we still need to resize images for mobile to fit more on a screen at a time. 

![Screen Shot 2021-04-13 at 12 28 05 PM](https://user-images.githubusercontent.com/7017118/114545330-bd796400-9c53-11eb-8fd5-ce33943e1499.png)

**Comment by Heydon** [comment]
@VirginiaDooley Hi! What is the issue here, exactly? That the photo is simply too big? I can try to find ways to scale it down decently.

**Comment by Heydon** [comment]
See https://github.com/DemocracyClub/design-system/pull/23 🙂

**Comment by pmk01** [comment]
I think this is now fixed on ballot view ... but photos on candidate profile pages are still too big on mobile.
