### ISSUE TITLE
Images, figures

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/design-system#3]
On the DC website we have a minimal `figure` style - it doesn't do anything apart from centre a `figcaption` under an image.

When I was looking at how this would look on the design system I noticed that images will break the width of the container - on the current site we have `max-width:100%` to prevent this - is this worth doing? In most cases it's better for the image to scale down rather than force side-scrolling

![Screenshot_2021-02-11 Page layout demo (Democracy Club Design System)](https://user-images.githubusercontent.com/242329/107627080-a8358880-6c56-11eb-8ceb-7d7e7f2dcdc3.png)

**Comment by Heydon** [comment]
@symroe Yes! That should be in the reset, will take care of that on the main branch now.

**Comment by Heydon** [comment]
Fixed on master
