### ISSUE TITLE
Use stack-smaller for text content

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/design-system#50]
Headers and bullet point lists are double spaced, and it's very annoying. Attached shows the minimum space between them. 

![Screenshot 2022-04-04 161617](https://user-images.githubusercontent.com/61510609/161575845-28bfb8e1-c88d-4ae5-b4a4-adb3e5f5566d.png)

**Comment by symroe** [comment]
This is an _implementation in projects_ thing rather than a bug with the design system. I think this screen shot relates to the website.

The task is to use `stack-smaller` in the container of the text on the page, rather than `stack`
